### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by jccq** [robcowart/kibana_plugins_list#1]
1) definitely recommended you add https://github.com/nreese/enhanced_tilemap
2) Siren platform component for Alerting and Reporting (Kibana compatible)    

thanks :)

**Comment by charlotth** [comment]
Hi ! 
I'd like to submit a new plugin in your list : https://github.com/datasweet-fr/kibana-datasweet-formula - enables calculated metric on any standard Kibana visualization. 
Kibana 5.6, 6.x

**Comment by robcowart** [comment]
done
