### ISSUE TITLE
coordinate map option doesnot show  up in kibana 7.8 

### ISSUE THREAD

**Issue by Divine1** [robcowart/kibana_plugins_list#14]
i have installed `kibana7.8` in windows10. The coordinated map option doesnot showup.
i have included the `geoip.location` data in logstash and it is reflected in kibana. i tried using map option to view the location based on coordinates in geoip. but that does not work. i checked out many videos/articles, everyone is using kibana `coordinate map` option to render the location on coordinate map. But i'm not able see it in my kibana setup

Please let me know what should i do to get it

![image](https://user-images.githubusercontent.com/10482177/90196500-90856080-dde9-11ea-8f26-731cb4ff4bf8.png)

**Comment by robcowart** [comment]
@Divine1 you can re-enable the coordinate map as described here... https://github.com/elastic/kibana/issues/75020#issuecomment-673953397
